WebApplication1/Models/DataContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class DataContext:DbContext
    {
        public DataContext() : base("Prueba")
        {

        }

        public DbSet<Ticket> Tickets { get; set; }
        public DbSet<Payment> Payments { get; set; }
    }
}

WebApplication1/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    [Table("PAY_PAYMENT")]
    public class Payment
    {
        public string TIC_ID { get; set; }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Required(ErrorMessage = "Debes ingresar este campo")]
        public int PAY_ID { get; set; }

        [Required(ErrorMessage = "Debes ingresar este campo")]
        //[DataType(DataType.Currency,ErrorMessage ="Ingresar formato valido")]
        public decimal PAY_TOTAL { get; set; }
        public int PAY_CANCELED { get; set; }

        public virtual Ticket Ticket { get; set; }
    }
}

WebApplication1/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    [Table("PAY_TICKET")]
    public class Ticket
    {
        [Key]
        [Required(ErrorMessage = "Debes ingresar este campo")]
        public string TIC_ID { get; set; }

        [Required(ErrorMessage = "Debes ingresar este campo")]
        //[DataType(DataType.Currency,ErrorMessage ="Ingresar formato correcto")]
        public decimal TIC_TOTALAMOUNT { get; set; }

        
        public virtual ICollection<Payment> Payments { get; set; }
    }
}

WebApplication1/Models/Tickets_PaymentsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Tickets_PaymentsViewModel
    {
        public string TIC_ID { get; set; }
        public decimal TIC_TOTALAMOUNT { get; set; }

        public decimal PAGADO { get; set; }
        public decimal FALTA { get; set; }
    }
}

WebApplication1/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class PaymentsController : Controller
    {
        private DataContext db = new DataContext();

        

        public ActionResult Create()
        {
            //Combo de tickets
            var tickets = new SelectList(db.Tickets, "TIC_ID", "TIC_ID");
            ViewBag.TIC_ID = tickets;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Payment payment)
        {
            //Combo de tickets
            ViewBag.TIC_ID = new SelectList(db.Tickets, "TIC_ID", "TIC_ID");
            if (ModelState.IsValid)
            {
                //Validar si pago ya fue dado de alta
                var pago = db.Payments.Find(payment.PAY_ID);
                if (pago != null)
                {
                    ViewBag.Mensaje = "Ya fue dado de alta este pago";
                    return View(payment);
                }


                //Validar que monto del ticket y monto de los pagos coincidan o no sea mayor
                var ticket = db.Tickets.Find(payment.TIC_ID);
                var pagos = db.Payments.Where(x => x.TIC_ID == payment.TIC_ID);

                var total_pagos = pagos.Count()==0 ? 0 : pagos.Sum(p=>p.PAY_TOTAL);

                //SI ya esta todo pagado
                if (ticket.TIC_TOTALAMOUNT == total_pagos)
                {
                    ViewBag.Mensaje = "Este ticket ya esta pagado";
                    return View(payment);
                }
                //Si es mayor los pagos al monto del ticket
                else if ((total_pagos + payment.PAY_TOTAL)>ticket.TIC_TOTALAMOUNT )
                {
                    ViewBag.Mensaje = "El monto ingresado supera el monto total del ticket";
                    return View(payment);
                }

                db.Payments.Add(payment);
                db.SaveChanges();

                try
                {
                    return RedirectToAction("Index", "Ticket", null);
                }
                catch (Exception)
                {

                    throw;
                }
                
            }
            
            return View(payment);
        }


    }
}

WebApplication1/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class TicketController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Tickets
        public ActionResult Index()
        {
            //Ejecutar Procedimiento almacenado para traer los datos de la BD
            var tickets = db.Database.SqlQuery<Tickets_PaymentsViewModel>("EXEC SP_TPAGOS");
            return View(tickets);
        }

        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(Ticket ticket)
        {

            if (ModelState.IsValid)
            {
                //Validar si ya fue registrado el ticket
                var validaticket = db.Tickets.Find(ticket.TIC_ID);
                if (validaticket != null)
                {
                    ViewBag.Mensaje = "Este ticket ya fue ingresado";
                    return View(ticket);
                }

                db.Tickets.Add(ticket);

                try
                {
                    db.SaveChanges();
                }
                catch (Exception)
                {

                    throw;
                }
                
                return RedirectToAction("Index");
            }
            return View(ticket);
            
        }


        public ActionResult Edit(string Id)
        {
            var ticket = db.Tickets.Find(Id);
            return View(ticket);
        }


        [HttpPost]
        public ActionResult Edit(Ticket ticket)
        {
            var reg = db.Tickets.Find(ticket.TIC_ID);
            reg.TIC_TOTALAMOUNT = ticket.TIC_TOTALAMOUNT;
            try
            {
                db.SaveChanges();
            }
            catch (Exception)
            {

                throw;
            }
            
            return RedirectToAction("Index");
        }

        public ActionResult Delete(string Id)
        {
            return View(db.Tickets.Find(Id));
        }


        [HttpPost]
        public ActionResult Delete(Ticket ticket2)
        {
            //Eliminar pagos correspondientes al ticket
            var pays = db.Payments.Where(x=>x.TIC_ID == ticket2.TIC_ID).ToList();
            db.Payments.RemoveRange(pays);

            try
            {
                db.SaveChanges();
            }
            catch (Exception)
            {

                throw;
            }
            
            return RedirectToAction("Index");
        }


        public ActionResult Details(string Id)
        {
            return View(db.Tickets.Find(Id));
        }
    }
}

WebApplication1/Views/Payments/Create.cshtml
@model WebApplication1.Models.Payment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@if (!string.IsNullOrEmpty(ViewBag.Mensaje))
{
    <div class="alert alert-danger">
        @ViewBag.Mensaje
    </div>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Payment</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.PAY_ID,htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PAY_ID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PAY_ID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TIC_ID, "TIC_ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TIC_ID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TIC_ID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PAY_TOTAL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PAY_TOTAL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PAY_TOTAL, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index","Ticket")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Tickets", "Index", "Ticket")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Ticket/Create.cshtml
@model WebApplication1.Models.Ticket

@{
    ViewBag.Title = "Index";
}

@if (!string.IsNullOrEmpty(ViewBag.Mensaje))
{
    <div class="alert alert-danger">
        @ViewBag.Mensaje
    </div>
}

<h2>Create</h2>
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.TIC_ID, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TIC_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TIC_ID)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TIC_TOTALAMOUNT, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TIC_TOTALAMOUNT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TIC_TOTALAMOUNT)
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Crear" class="btn btn-success" />
        </div>
    </div>
}

WebApplication1/Views/Ticket/Delete.cshtml
@model WebApplication1.Models.Ticket

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TIC_ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TIC_ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TIC_TOTALAMOUNT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIC_TOTALAMOUNT)
        </dd>

    </dl>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    TIC_ID
                </th>
                <th>
                    PAY_TOTAL
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var row in Model.Payments)
            {
                <tr>
                    <td>@row.PAY_ID</td>
                    <td>@row.PAY_TOTAL</td>
                </tr>
            }
        </tbody>
    </table>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.HiddenFor(model => model.TIC_ID)
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Ticket/Details.cshtml
@model WebApplication1.Models.Ticket

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TIC_ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TIC_ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TIC_TOTALAMOUNT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIC_TOTALAMOUNT)
        </dd>

    </dl>
</div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                TIC_ID
            </th>
            <th>
                PAY_TOTAL
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var row in Model.Payments)
        {
        <tr>
            <td>@row.PAY_ID</td>
            <td>@row.PAY_TOTAL</td>
        </tr>
        }
    </tbody>
</table>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TIC_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/Views/Ticket/Edit.cshtml
@model WebApplication1.Models.Ticket

@{
    ViewBag.Title = "Index";
}

<h2>Create</h2>
@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.TIC_ID, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TIC_ID)
                @Html.ValidationMessageFor(model => model.TIC_ID)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TIC_TOTALAMOUNT, htmlAttributes: new { @class = "col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TIC_TOTALAMOUNT)
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
}

WebApplication1/Views/Ticket/Index.cshtml
@model IEnumerable<WebApplication1.Models.Tickets_PaymentsViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<p>
    @Html.ActionLink("Create New", "Create") |
    @Html.ActionLink("Add Payment","Create","Payments",null,null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TIC_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TIC_TOTALAMOUNT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PAGADO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FALTA)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TIC_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TIC_TOTALAMOUNT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PAGADO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FALTA)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.TIC_ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.TIC_ID }) |
                @if (item.PAGADO > 0)
                {
                    @Html.ActionLink("Delete", "Delete", new { id = item.TIC_ID })
                }

            </td>
        </tr>
    }

</table>